"""Static HTML dashboard - the 'operating system for autonomous intelligence' view.

Aggregates a run into one index.html: benchmark tiles, a failure-pattern panel,
and a table of every task linking to its interactive trajectory graph.
"""
from __future__ import annotations

import html
import json
from collections import Counter
from pathlib import Path

from .metrics import aggregate
from .trajectory import Trajectory
from .util import trim

_CSS = """
body{margin:0;font-family:Arial,Helvetica,sans-serif;background:#0f172a;color:#e2e8f0}
header{padding:16px 22px;background:#1e293b;border-bottom:1px solid #334155}
header h1{margin:0;font-size:20px}
header .sub{color:#94a3b8;font-size:13px;margin-top:4px}
.tiles{display:flex;flex-wrap:wrap;gap:12px;padding:16px 22px}
.tile{background:#111827;border:1px solid #334155;border-radius:10px;padding:12px 16px;min-width:150px}
.tile .v{font-size:24px;font-weight:700}
.tile .k{font-size:11px;color:#94a3b8;text-transform:uppercase;letter-spacing:.04em}
.tile.good .v{color:#4ade80}.tile.warn .v{color:#fbbf24}
section{padding:6px 22px 22px}
h2{font-size:15px;color:#cbd5e1;border-bottom:1px solid #334155;padding-bottom:6px}
table{width:100%;border-collapse:collapse;font-size:13px}
th,td{text-align:left;padding:7px 9px;border-bottom:1px solid #1f2937}
th{color:#94a3b8;font-weight:600}
tr:hover{background:#111827}
.badge{padding:2px 9px;border-radius:9px;font-size:11px;font-weight:700}
.ok{background:#16a34a;color:#04210f}.fail{background:#dc2626;color:#2a0606}
a{color:#60a5fa;text-decoration:none}a:hover{text-decoration:underline}
.pat{display:inline-block;background:#111827;border:1px solid #334155;border-radius:8px;padding:4px 10px;margin:4px 6px 0 0;font-size:12px}
.foot{color:#64748b;font-size:11px;padding:10px 22px}
"""


def _tile(k, v, cls=""):
    return f'<div class="tile {cls}"><div class="v">{v}</div><div class="k">{k}</div></div>'


def build_dashboard(trajs: list[Trajectory], out_dir: Path, *,
                    experiment: str = "helix", config_note: str = "") -> Path:
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    m = aggregate(trajs)

    tgc = m.get("task_goal_completion") or 0
    tiles = "".join([
        _tile("Task Goal Completion", f"{tgc * 100:.1f}%", "good" if tgc >= 0.5 else "warn"),
        _tile("Solved", f"{m['solved']}/{m['num_tasks']}"),
        _tile("Recovery rate", m.get("recovery_rate")),
        _tile("Planning eff.", m.get("planning_efficiency")),
        _tile("World-model acc", m.get("world_model_accuracy")),
        _tile("Knowledge reuse", m.get("knowledge_reuse_rate")),
        _tile("Avg steps", m.get("avg_steps")),
        _tile("Total cost", f"${m.get('total_cost_usd')}"),
    ])

    # failure patterns across failed tasks
    pat = Counter()
    for t in trajs:
        if not t.solved:
            for o in t.nodes_of("outcome"):
                if o.status == "error" and o.data.get("error_type"):
                    pat[o.data["error_type"]] += 1
    pat_html = ("".join(f'<span class="pat">{html.escape(k)} &times; {v}</span>'
                        for k, v in pat.most_common(12))
                or '<span class="pat">no failures recorded</span>')

    rows = []
    for t in sorted(trajs, key=lambda x: (not x.solved, x.task_id)):
        s = t.summary()
        badge = '<span class="badge ok">SOLVED</span>' if t.solved else '<span class="badge fail">FAILED</span>'
        graph = f"graphs/{t.task_id}.html"
        svg = f"graphs/{t.task_id}.svg"
        rows.append(
            "<tr>"
            f"<td>{badge}</td>"
            f"<td><code>{html.escape(t.task_id)}</code></td>"
            f"<td>{html.escape(trim(t.instruction, 80))}</td>"
            f"<td>{s['num_steps']}</td><td>{s['num_errors']}</td>"
            f"<td>{s['num_recoveries']}</td>"
            f"<td>{s['world_model_accuracy']}</td>"
            f"<td>${s['total_cost_usd']}</td>"
            f'<td><a href="{graph}">graph</a> &middot; <a href="{svg}">svg</a></td>'
            "</tr>"
        )

    page = f"""<!DOCTYPE html><html><head><meta charset="utf-8">
<title>HELIX - {html.escape(experiment)}</title><style>{_CSS}</style></head><body>
<header>
  <h1>HELIX &mdash; Trajectory Intelligence Platform</h1>
  <div class="sub">experiment: <b>{html.escape(experiment)}</b> &nbsp;|&nbsp; {html.escape(config_note)}</div>
</header>
<div class="tiles">{tiles}</div>
<section>
  <h2>Failure patterns (across failed tasks)</h2>
  <div>{pat_html}</div>
</section>
<section>
  <h2>Tasks &amp; trajectories</h2>
  <table>
    <tr><th>status</th><th>task</th><th>instruction</th><th>steps</th><th>errors</th>
        <th>recov</th><th>WM-acc</th><th>cost</th><th>trajectory</th></tr>
    {''.join(rows)}
  </table>
</section>
<div class="foot">Generated by HELIX. Each trajectory is a graph of State&rarr;Decision&rarr;Action&rarr;Outcome,
monitored live, healed on failure, and indexed for reuse.</div>
</body></html>"""

    index = out_dir / "index.html"
    index.write_text(page, encoding="utf-8")
    (out_dir / "metrics.json").write_text(json.dumps(m, indent=2), encoding="utf-8")
    return index
